/*
# 11+ Quest: English Question Bank Expansion

Adds 105 new english questions (15 per topic × 7 topics), even spread across
difficulty 1/2/3 (5 each per topic), spanning Year 3-6 ability range.

Purely additive — existing seed questions (migration 002) are untouched.
correct_answer uses the integer index format (0-3) into `options`.
*/

INSERT INTO questions (category, topic, question_text, options, correct_answer, explanation, difficulty, age_range) VALUES

-- ═══════════════════════════════════════════════════════════════════════
-- GRAMMAR (15)
-- ═══════════════════════════════════════════════════════════════════════
('english', 'Grammar', 'Which word is a verb in this sentence: "The dog barked loudly"?', '["Dog", "Barked", "Loudly", "The"]', 1, 'A verb shows an action. "Barked" is the action the dog did', 1, '8-9'),
('english', 'Grammar', 'Which sentence is in the past tense?', '["I walk to school", "I will walk to school", "I walked to school", "I am walking to school"]', 2, '"Walked" shows the action already happened, which is the past tense', 1, '8-9'),
('english', 'Grammar', 'Which word is a pronoun?', '["Quickly", "She", "Jump", "Happy"]', 1, 'A pronoun replaces a noun. "She" stands in for a person''s name', 1, '8-9'),
('english', 'Grammar', 'Choose the correct plural of "child".', '["Childs", "Childes", "Children", "Childrens"]', 2, '"Children" is an irregular plural — it does not simply add -s or -es like most words', 1, '8-9'),
('english', 'Grammar', 'Which word is an adjective in: "The tall boy ran fast"?', '["Tall", "Boy", "Ran", "Fast"]', 0, 'An adjective describes a noun. "Tall" describes the boy', 1, '8-9'),
('english', 'Grammar', 'Which sentence uses the correct verb form?', '["She has went home", "She has gone home", "She have gone home", "She has goed home"]', 1, '"Gone" is the correct past participle of "go", used with "has/have"', 2, '9-10'),
('english', 'Grammar', 'Which word correctly completes: "Neither the cat nor the dogs ___ hungry."', '["is", "are", "be", "was"]', 1, 'With "neither...nor", the verb agrees with the noun closest to it. "Dogs" is plural, so "are" is correct', 2, '9-10'),
('english', 'Grammar', 'Which is the correct comparative form of "good"?', '["Gooder", "More good", "Better", "Best"]', 2, '"Good" has an irregular comparative form: "better" (not "gooder")', 2, '9-10'),
('english', 'Grammar', 'Which sentence uses an adverb correctly?', '["She sang beautiful", "She sang beautifully", "She sang beauty", "She sang beautify"]', 1, 'An adverb describes a verb. "Beautifully" describes how she sang', 2, '9-10'),
('english', 'Grammar', 'Identify the conjunction in: "I wanted to go, but it was raining."', '["Wanted", "Go", "But", "Raining"]', 2, 'A conjunction joins two clauses together. "But" connects the two ideas in this sentence', 2, '9-10'),
('english', 'Grammar', 'Which sentence correctly uses the subjunctive mood?', '["If I was rich, I would travel", "If I were rich, I would travel", "If I am rich, I would travel", "If I be rich, I would travel"]', 1, 'The subjunctive mood uses "were" (not "was") for hypothetical situations, even with singular subjects like "I"', 3, '10-11'),
('english', 'Grammar', 'Which sentence demonstrates correct subject-verb agreement?', '["The committee are meeting today", "The committee is meeting today", "The committee were meeting today", "The committee be meeting today"]', 1, '"Committee" is a collective noun treated as singular in British English, so it takes "is"', 3, '10-11'),
('english', 'Grammar', 'Which word in this sentence is a relative pronoun: "The book that I borrowed was excellent"?', '["Book", "That", "Borrowed", "Excellent"]', 1, '"That" introduces a relative clause, connecting "the book" to more information about it', 3, '10-11'),
('english', 'Grammar', 'Identify the correct use of the passive voice.', '["The cat chased the mouse", "The mouse was chased by the cat", "The mouse chases the cat", "Chasing the mouse, the cat ran"]', 1, 'In the passive voice, the subject receives the action rather than performing it. Here, the mouse receives the action of being chased', 3, '10-11'),
('english', 'Grammar', 'Which sentence correctly uses a dangling modifier-free structure?', '["Walking to school, the rain started", "Walking to school, I got caught in the rain", "The rain started, walking to school", "Walking to school the rain fell"]', 1, 'The modifier "walking to school" must describe the subject right after the comma — "I" was walking, not "the rain"', 3, '10-11'),

-- ═══════════════════════════════════════════════════════════════════════
-- COMPREHENSION (15)
-- ═══════════════════════════════════════════════════════════════════════
('english', 'Comprehension', 'If a story says "Tom felt his stomach grumble", what does this most likely mean?', '["Tom was scared", "Tom was hungry", "Tom was tired", "Tom was angry"]', 1, 'A grumbling stomach is a common way of describing the feeling of hunger', 1, '8-9'),
('english', 'Comprehension', 'In a passage describing a "gloomy, rain-soaked street", what mood is being created?', '["Cheerful", "Exciting", "Gloomy", "Funny"]', 2, 'Words like "gloomy" and "rain-soaked" directly create a sad or dreary mood', 1, '8-9'),
('english', 'Comprehension', 'If a character "trudged wearily home", how were they likely feeling?', '["Excited", "Tired", "Joyful", "Curious"]', 1, '"Trudged" and "wearily" both suggest the character was tired or worn out', 1, '8-9'),
('english', 'Comprehension', 'A text says "the sun blazed overhead". What does "blazed" suggest about the weather?', '["It was cold", "It was very hot", "It was raining", "It was windy"]', 1, '"Blazed" describes something burning intensely, suggesting very hot, strong sunshine', 1, '8-9'),
('english', 'Comprehension', 'If a passage states a character "whispered nervously", what can you infer?', '["They were confident", "They were anxious", "They were loud", "They were happy"]', 1, '"Whispered nervously" suggests the character was anxious or worried about something', 1, '8-9'),
('english', 'Comprehension', 'A passage describes a character as having "a heart of stone". What does this most likely mean?', '["They are physically strong", "They are unkind or unfeeling", "They are very old", "They have a heart condition"]', 1, 'This is a figurative expression meaning the character lacks compassion or warmth', 2, '9-10'),
('english', 'Comprehension', 'If the author writes "the silence was deafening", what literary technique is being used?', '["Simile", "Oxymoron", "Alliteration", "Rhyme"]', 1, 'An oxymoron combines two contradictory ideas — silence cannot literally be "deafening", which creates emphasis', 2, '9-10'),
('english', 'Comprehension', 'A character says, "I suppose it could have been worse," after losing a competition. What does this tone suggest?', '["Pure joy", "Reluctant acceptance", "Total despair", "Anger"]', 1, 'The phrase "I suppose" suggests the character is grudgingly accepting the situation rather than being thrilled or devastated', 2, '9-10'),
('english', 'Comprehension', 'If a story\'s opening line is "It was the best of times, it was the worst of times," what technique is used?', '["Metaphor", "Contrast", "Onomatopoeia", "Personification"]', 1, 'This line uses contrast, placing two opposite ideas side by side for effect', 2, '9-10'),
('english', 'Comprehension', 'A passage describes rain as "the sky''s tears". What technique is this?', '["Simile", "Personification", "Hyperbole", "Alliteration"]', 1, 'This gives the sky a human quality (crying) without using "like" or "as", which makes it personification rather than simile', 2, '9-10'),
('english', 'Comprehension', 'In a text, a character is described as having eyes that "pierced like daggers". Identify the technique.', '["Simile", "Metaphor", "Onomatopoeia", "Alliteration"]', 0, 'This is a simile because it uses "like" to compare the eyes to daggers', 3, '10-11'),
('english', 'Comprehension', 'If a narrator says "Little did I know what awaited me," what narrative technique is being used?', '["Flashback", "Foreshadowing", "Flashforward", "Direct speech"]', 1, 'This phrase hints at future events without revealing them, which is foreshadowing', 3, '10-11'),
('english', 'Comprehension', 'A character\'s dialogue is full of short, clipped sentences during an argument. What does this most likely convey?', '["Calmness", "Tension or anger", "Boredom", "Confusion"]', 1, 'Short, clipped sentences often convey tension, urgency, or anger in dialogue', 3, '10-11'),
('english', 'Comprehension', 'If a passage is written entirely from inside one character\'s thoughts, what point of view is being used?', '["Third person omniscient", "First person", "Second person", "Third person limited"]', 1, 'A passage focused entirely on one character''s inner thoughts, told as "I", is first person narration', 3, '10-11'),
('english', 'Comprehension', 'A writer repeats the phrase "Never again" three times across a passage about war. What is the effect of this repetition?', '["It confuses the reader", "It emphasises the message", "It shortens the passage", "It has no effect"]', 1, 'Repetition is a deliberate technique used to emphasise and reinforce a key message or feeling', 3, '10-11'),

-- ═══════════════════════════════════════════════════════════════════════
-- PUNCTUATION (15)
-- ═══════════════════════════════════════════════════════════════════════
('english', 'Punctuation', 'Which sentence has correct punctuation?', '["What time is it", "What time is it.", "What time is it?", "what time is it?"]', 2, 'Questions must start with a capital letter and end with a question mark', 1, '8-9'),
('english', 'Punctuation', 'Which sentence uses a comma correctly?', '["I like apples oranges and pears", "I like apples, oranges, and pears", "I like, apples oranges and pears", "I like apples oranges, and pears"]', 1, 'Commas separate items in a list: "apples, oranges, and pears"', 1, '8-9'),
('english', 'Punctuation', 'Which sentence ends correctly with an exclamation mark?', '["Watch out.", "Watch out", "Watch out!", "Watch out?"]', 2, 'An exclamation mark is used to show strong feeling or urgency, like a warning', 1, '8-9'),
('english', 'Punctuation', 'Which word needs an apostrophe: "The dogs bone was buried."?', '["Dogs", "Bone", "Was", "Buried"]', 0, '"Dog''s" needs an apostrophe to show the bone belongs to the dog (possession)', 1, '8-9'),
('english', 'Punctuation', 'Speech marks should be placed directly around which part of this sentence: She said, I am happy?', '["The whole sentence", "Just the word said", "Only the spoken words: I am happy", "Nothing needs speech marks"]', 2, 'Speech marks go directly around the exact words that were spoken, here: I am happy', 1, '8-9'),
('english', 'Punctuation', 'Which sentence uses a colon correctly?', '["I need the following: milk, eggs and bread.", "I need the following, milk, eggs and bread.", "I need the following; milk, eggs and bread.", "I need the following milk eggs and bread."]', 0, 'A colon introduces a list. ": milk, eggs and bread" correctly follows "the following"', 2, '9-10'),
('english', 'Punctuation', 'Which sentence correctly uses an apostrophe for a plural possessive?', '["The dogs'' bones were buried.", "The dog''s'' bones were buried.", "The dogs bones'' were buried.", "The dog''s bones were buried."]', 0, 'For a plural noun ending in "s" (dogs), the apostrophe goes after the "s": dogs''', 2, '9-10'),
('english', 'Punctuation', 'Which sentence uses a semicolon correctly?', '["I was tired; I went to bed early.", "I was tired, I went to bed early;", "I was tired; and I went to bed early.", "I was; tired I went to bed early."]', 0, 'A semicolon joins two related, complete sentences without needing a conjunction: "I was tired; I went to bed early"', 2, '9-10'),
('english', 'Punctuation', 'Which sentence uses brackets correctly?', '["My brother (who is ten) loves football.", "My brother who is ten) loves football.", "My brother (who is ten loves football.", "My (brother who is ten) loves football."]', 0, 'Brackets enclose extra information that could be removed without changing the main meaning: "(who is ten)"', 2, '9-10'),
('english', 'Punctuation', 'Identify the sentence with correctly placed commas around an interrupting phrase.', '["My teacher Mrs Jones, is very kind.", "My teacher, Mrs Jones is very kind.", "My teacher, Mrs Jones, is very kind.", "My teacher Mrs Jones is, very kind."]', 2, 'Commas should surround the interrupting phrase "Mrs Jones" on both sides', 2, '9-10'),
('english', 'Punctuation', 'Which sentence correctly uses a hyphen?', '["The well known author signed books.", "The well-known author signed books.", "The well, known author signed books.", "The well; known author signed books."]', 1, 'A hyphen joins "well" and "known" to form a single compound adjective describing the author', 3, '10-11'),
('english', 'Punctuation', 'Which sentence uses an em dash correctly to show an abrupt interruption?', '["I was about to leave \u2014 when the phone rang.", "I was about to leave, when the phone rang.", "I was about to leave; when the phone rang.", "I was about to leave: when the phone rang."]', 0, 'An em dash effectively shows a sudden interruption or break in thought', 3, '10-11'),
('english', 'Punctuation', 'When a title or quotation appears inside spoken dialogue that already uses double speech marks, what should the inner quotation use?', '["Double speech marks, same as the outer one", "Single quote marks", "No punctuation at all", "Square brackets"]', 1, 'When a quotation appears inside another quotation, the inner one uses single quote marks while the outer dialogue uses double speech marks, to keep the two visually distinct', 3, '10-11'),
('english', 'Punctuation', 'Which sentence correctly uses an ellipsis to show hesitation?', '["I think... maybe we should go.", "I think, maybe we should go.", "I think; maybe we should go.", "I think: maybe we should go."]', 0, 'An ellipsis (three dots) shows a pause, hesitation, or trailing off in speech or thought', 3, '10-11'),
('english', 'Punctuation', 'Which sentence correctly uses a colon to introduce an explanation?', '["She had one goal: to win.", "She had one goal, to win.", "She had one goal; to win.", "She had one goal to win."]', 0, 'A colon can introduce an explanation or elaboration of what came before it: "one goal: to win"', 3, '10-11'),

-- ═══════════════════════════════════════════════════════════════════════
-- SPELLING (15)
-- ═══════════════════════════════════════════════════════════════════════
('english', 'Spelling', 'Which word is spelled correctly?', '["Becuase", "Because", "Becuse", "Beacause"]', 1, '"Because" is the correct spelling — remember "big elephants can always understand small elephants"', 1, '8-9'),
('english', 'Spelling', 'Which word is spelled correctly?', '["Freind", "Friend", "Freand", "Frend"]', 1, '"Friend" follows an exception to "i before e" — remember it as "fri-end"', 1, '8-9'),
('english', 'Spelling', 'Which word is spelled correctly?', '["Beautyfull", "Beautiful", "Beutiful", "Beautifull"]', 1, '"Beautiful" ends in -iful, not -ifull (only one "l")', 1, '8-9'),
('english', 'Spelling', 'Which word is spelled correctly?', '["Diffrent", "Differant", "Different", "Differnt"]', 2, '"Different" has an "e" before the final "nt" — diff-er-ent', 1, '8-9'),
('english', 'Spelling', 'Which word is spelled correctly?', '["Wich", "Which", "Whitch", "Whihc"]', 1, '"Which" starts with "wh" and includes a silent "h" after the "w"', 1, '8-9'),
('english', 'Spelling', 'Which word is spelled correctly?', '["Necessary", "Neccessary", "Necesary", "Neccesary"]', 0, '"Necessary" has one "c" and two "s"s — remember "one collar, two socks"', 2, '9-10'),
('english', 'Spelling', 'Which word is spelled correctly?', '["Definately", "Definitly", "Definitely", "Definatly"]', 2, '"Definitely" contains the word "finite" inside it: defi-NITE-ly', 2, '9-10'),
('english', 'Spelling', 'Which word is spelled correctly?', '["Seperate", "Separate", "Saparate", "Seperete"]', 1, '"Separate" has "a rat" hidden in the middle: sep-A-RA-te', 2, '9-10'),
('english', 'Spelling', 'Which word is spelled correctly?', '["Embarass", "Embarrass", "Embaras", "Embarras"]', 1, '"Embarrass" has a double "r" and a double "s"', 2, '9-10'),
('english', 'Spelling', 'Which word is spelled correctly?', '["Accomodate", "Acommodate", "Accommodate", "Acomodate"]', 2, '"Accommodate" has a double "c" and a double "m"', 2, '9-10'),
('english', 'Spelling', 'Which word is spelled correctly?', '["Conscientious", "Consientious", "Conscienscious", "Concientious"]', 0, '"Conscientious" comes from "conscience" — keep the "sc" pattern throughout', 3, '10-11'),
('english', 'Spelling', 'Which word is spelled correctly?', '["Privilage", "Priviledge", "Privilege", "Previlege"]', 2, '"Privilege" has no "d" — a common mistake is adding one before the "g"', 3, '10-11'),
('english', 'Spelling', 'Which word is spelled correctly?', '["Maintainance", "Maintenance", "Maintainence", "Maintnance"]', 1, '"Maintenance" is spelled with "ten" in the middle, not "tain"', 3, '10-11'),
('english', 'Spelling', 'Which word is spelled correctly?', '["Rythm", "Rhythym", "Rhythm", "Rhytm"]', 2, '"Rhythm" has no vowels in its second syllable — it''s "rhy-thm"', 3, '10-11'),
('english', 'Spelling', 'Which word is spelled correctly?', '["Occassion", "Ocassion", "Occasion", "Occasionn"]', 2, '"Occasion" has a double "c" but only a single "s"', 3, '10-11'),

-- ═══════════════════════════════════════════════════════════════════════
-- SENTENCE STRUCTURE (15)
-- ═══════════════════════════════════════════════════════════════════════
('english', 'Sentence Structure', 'Which of these is a complete sentence?', '["Running fast.", "The boy ran fast.", "Fast and far.", "Because he ran."]', 1, 'A complete sentence needs a subject and a verb. "The boy ran fast" has both', 1, '8-9'),
('english', 'Sentence Structure', 'Identify the subject in: "The cat sat on the mat."', '["The cat", "Sat", "On", "The mat"]', 0, 'The subject is who or what the sentence is about. Here, it''s "the cat"', 1, '8-9'),
('english', 'Sentence Structure', 'Which sentence is a question?', '["The sky is blue.", "Is the sky blue?", "The sky is blue!", "Blue sky."]', 1, 'A question is marked by a question mark and asks something, like "Is the sky blue?"', 1, '8-9'),
('english', 'Sentence Structure', 'Which is an example of a command sentence?', '["The dog runs fast.", "Does the dog run fast?", "Run, dog, run!", "What a fast dog!"]', 2, 'A command tells someone to do something. "Run, dog, run!" instructs an action', 1, '8-9'),
('english', 'Sentence Structure', 'Which sentence is an exclamation?', '["The fireworks are loud.", "Are the fireworks loud?", "What loud fireworks!", "Listen to the fireworks."]', 2, 'An exclamation expresses strong feeling and ends with "!" — "What loud fireworks!"', 1, '8-9'),
('english', 'Sentence Structure', 'Which sentence is a compound sentence?', '["I like tea.", "I like tea and coffee.", "I like tea, but I prefer coffee.", "Tea is nice."]', 2, 'A compound sentence joins two complete ideas with a conjunction like "but": "I like tea, but I prefer coffee"', 2, '9-10'),
('english', 'Sentence Structure', 'Identify the subordinate clause in: "Although it was raining, we went outside."', '["Although it was raining", "We went outside", "It was raining", "Went outside"]', 0, 'A subordinate clause cannot stand alone. "Although it was raining" depends on the rest of the sentence', 2, '9-10'),
('english', 'Sentence Structure', 'Which sentence uses a simple sentence structure?', '["The dog barked.", "The dog barked, and the cat ran.", "Although tired, the dog barked.", "The dog, which was tired, barked."]', 0, 'A simple sentence has just one subject and one verb, with no extra clauses: "The dog barked"', 2, '9-10'),
('english', 'Sentence Structure', 'Which sentence correctly joins two ideas using a conjunction?', '["She was tired she went to bed.", "She was tired, so she went to bed.", "She was tired. So she went to bed she did.", "Tired she was, bed went to."]', 1, '"So" is a conjunction that correctly joins the two related ideas with a comma before it', 2, '9-10'),
('english', 'Sentence Structure', 'Which sentence is grammatically complete (not a fragment)?', '["Walking through the park.", "Because it was sunny.", "She walked through the park.", "Through the park, sunny."]', 2, '"She walked through the park" has both a subject and a verb, making it complete', 2, '9-10'),
('english', 'Sentence Structure', 'Which sentence demonstrates correct use of a complex sentence with a relative clause?', '["The book was good. I read it.", "The book, which I read, was good.", "The book was good I read it.", "Reading it, the book was good."]', 1, '"Which I read" is a relative clause adding detail to "the book" within one complex sentence', 3, '10-11'),
('english', 'Sentence Structure', 'Identify the main clause in: "Although she was nervous, she gave an excellent speech."', '["Although she was nervous", "She gave an excellent speech", "She was nervous", "An excellent speech"]', 1, 'The main clause can stand alone as a complete sentence: "She gave an excellent speech"', 3, '10-11'),
('english', 'Sentence Structure', 'Which sentence correctly avoids a comma splice?', '["I was hungry, I ate lunch.", "I was hungry; I ate lunch.", "I was hungry I ate lunch.", "I was hungry, and, I ate lunch."]', 1, 'A semicolon correctly joins two complete sentences without creating a comma splice (which incorrectly uses just a comma)', 3, '10-11'),
('english', 'Sentence Structure', 'Which sentence uses parallel structure correctly?', '["She likes swimming, running, and to cycle.", "She likes swimming, running, and cycling.", "She likes to swim, running, and cycle.", "She likes swim, run, and cycling."]', 1, 'Parallel structure requires all items in a list to follow the same grammatical form — all three end in "-ing"', 3, '10-11'),
('english', 'Sentence Structure', 'Which sentence correctly uses a semicolon to join two independent clauses with a linking adverb?', '["I was late; however, I still caught the train.", "I was late, however I still caught the train.", "I was late; however I still caught the train", "I was late however; I still caught the train."]', 0, 'A semicolon before a linking adverb like "however", followed by a comma, correctly joins two independent clauses', 3, '10-11'),

-- ═══════════════════════════════════════════════════════════════════════
-- READING (15)
-- ═══════════════════════════════════════════════════════════════════════
('english', 'Reading', 'What is the main purpose of a recipe?', '["To entertain", "To give instructions", "To persuade", "To describe a feeling"]', 1, 'A recipe is a set of instructions explaining how to make something, usually food', 1, '8-9'),
('english', 'Reading', 'What type of text is a weather forecast?', '["Fiction", "Non-fiction", "Poetry", "Drama"]', 1, 'A weather forecast presents real, factual information, making it non-fiction', 1, '8-9'),
('english', 'Reading', 'If a book is described as a "biography", what is it about?', '["An invented story", "A real person''s life", "A set of poems", "A play"]', 1, 'A biography is a true account of a real person''s life, written by someone else', 1, '8-9'),
('english', 'Reading', 'What is the purpose of a persuasive text?', '["To inform only", "To convince the reader of something", "To entertain with jokes", "To list facts only"]', 1, 'Persuasive writing aims to convince the reader to agree with an opinion or take an action', 1, '8-9'),
('english', 'Reading', 'What do you call the main message or idea behind a story?', '["The setting", "The theme", "The character", "The title"]', 1, 'The theme is the central idea or message that runs through a story', 1, '8-9'),
('english', 'Reading', 'What is the term for the order in which events happen in a story?', '["Setting", "Plot", "Genre", "Dialogue"]', 1, 'The plot is the sequence of events that make up the story', 2, '9-10'),
('english', 'Reading', 'In a non-fiction text about volcanoes, what would you expect to find?', '["Made-up characters", "Factual information and diagrams", "A fairy-tale ending", "Rhyming verses"]', 1, 'Non-fiction texts present real information, often supported by facts and diagrams', 2, '9-10'),
('english', 'Reading', 'What is a "skim read" used for?', '["Reading every word slowly", "Getting a quick general idea of a text", "Memorising a text word for word", "Reading aloud to others"]', 1, 'Skimming means quickly looking through a text to get the general idea, without reading every word', 2, '9-10'),
('english', 'Reading', 'If an instruction text uses numbered steps, what is the purpose of the numbers?', '["To decorate the page", "To show the order tasks should be done", "To count the words", "To show how long it takes"]', 1, 'Numbered steps show the reader the correct order to follow the instructions', 2, '9-10'),
('english', 'Reading', 'What is the difference between a fact and an opinion?', '["A fact can be proven true; an opinion is a personal belief", "A fact is always longer than an opinion", "An opinion is always written in capital letters", "There is no difference"]', 0, 'A fact can be checked and proven, while an opinion expresses someone''s personal view or feeling', 2, '9-10'),
('english', 'Reading', 'When reading a newspaper report, what is the purpose of the headline?', '["To summarise the story and grab attention", "To list the author''s name", "To show the date only", "To advertise other newspapers"]', 0, 'A headline is designed to summarise the story briefly while attracting the reader''s attention', 3, '10-11'),
('english', 'Reading', 'What is meant by the term "bias" in a text?', '["Writing only true facts", "An unfair preference for one side or view", "Using long words", "Writing in rhyme"]', 1, 'Bias means showing an unfair preference for one perspective, often by leaving out other viewpoints', 3, '10-11'),
('english', 'Reading', 'In an autobiography, who is telling the story?', '["A narrator about someone else", "The subject writing about their own life", "An unknown author", "A fictional character"]', 1, 'An autobiography is written by the subject themselves, about their own life', 3, '10-11'),
('english', 'Reading', 'What is the purpose of a sub-heading in a non-fiction text?', '["To make the page longer", "To break the text into organised sections", "To replace the main heading", "To confuse the reader"]', 1, 'Sub-headings organise a text into clear sections, helping readers find information quickly', 3, '10-11'),
('english', 'Reading', 'What does it mean to "infer" something from a text?', '["To copy it directly", "To work out a meaning that isn''t directly stated", "To ignore the text", "To read it aloud"]', 1, 'Inferring means using clues in the text to work out something the author hasn''t stated directly', 3, '10-11'),

-- ═══════════════════════════════════════════════════════════════════════
-- CREATIVE WRITING (15)
-- ═══════════════════════════════════════════════════════════════════════
('english', 'Creative Writing', 'Which sentence uses the most interesting description?', '["The dog ran.", "The dog ran fast.", "The shaggy dog bounded joyfully across the field.", "The dog moved."]', 2, 'This sentence uses vivid adjectives ("shaggy") and adverbs ("joyfully") to create a clearer picture', 1, '8-9'),
('english', 'Creative Writing', 'What is a simile?', '["A word that sounds like its meaning", "A comparison using ''like'' or ''as''", "A made-up word", "A type of punctuation"]', 1, 'A simile compares two things using "like" or "as", e.g. "as brave as a lion"', 1, '8-9'),
('english', 'Creative Writing', 'Which of these is an example of a simile?', '["The wind howled.", "Her smile was sunshine.", "He ran like the wind.", "Time flew by."]', 2, '"Like the wind" makes this a simile, comparing his running speed to wind using "like"', 1, '8-9'),
('english', 'Creative Writing', 'What does "setting" mean in a story?', '["The characters in the story", "Where and when the story takes place", "The problem in the story", "The ending of the story"]', 1, 'The setting describes the time and place in which a story happens', 1, '8-9'),
('english', 'Creative Writing', 'Which word would best describe a "spine-chilling" story?', '["Funny", "Scary", "Happy", "Boring"]', 1, '"Spine-chilling" describes something frightening enough to give you shivers', 1, '8-9'),
('english', 'Creative Writing', 'What is a metaphor?', '["A direct comparison without using ''like'' or ''as''", "A rhyme at the end of a line", "A question asked for effect", "A list of adjectives"]', 0, 'A metaphor describes something as if it were something else, without using "like" or "as", e.g. "Time is a thief"', 2, '9-10'),
('english', 'Creative Writing', 'Which sentence uses personification?', '["The wind was strong.", "The wind howled angrily through the trees.", "The wind blew north.", "It was windy today."]', 1, 'Personification gives human qualities (like anger and howling) to something non-human, like the wind', 2, '9-10'),
('english', 'Creative Writing', 'What is the effect of using short sentences in an action scene?', '["It slows the pace down", "It creates a sense of speed and urgency", "It makes the writing boring", "It has no effect on pace"]', 1, 'Short sentences speed up the pace of writing, creating tension or urgency in action scenes', 2, '9-10'),
('english', 'Creative Writing', 'Which technique uses words that sound like the noise they describe?', '["Simile", "Onomatopoeia", "Metaphor", "Alliteration"]', 1, 'Onomatopoeia uses words like "buzz" or "crash" that imitate the sound they represent', 2, '9-10'),
('english', 'Creative Writing', 'Which sentence uses alliteration?', '["The big brown bear bounded by.", "The cat sat on the mat.", "Rain fell from the sky.", "She walked to the shop."]', 0, 'Alliteration repeats the same starting sound — here, the repeated "b" sound in "big brown bear bounded"', 2, '9-10'),
('english', 'Creative Writing', 'What is the purpose of a "hook" at the start of a story?', '["To end the story", "To grab the reader''s attention immediately", "To introduce the setting only", "To list all characters"]', 1, 'A hook is an opening line or scene designed to immediately capture the reader''s interest', 3, '10-11'),
('english', 'Creative Writing', 'Which technique builds suspense most effectively in a story?', '["Revealing the ending early", "Withholding key information from the reader", "Using only short, simple sentences throughout", "Describing the setting in great detail only"]', 1, 'Suspense is built by withholding important information, making the reader want to keep reading to find out what happens', 3, '10-11'),
('english', 'Creative Writing', 'What is the effect of writing in the present tense rather than the past tense?', '["It makes the story feel distant", "It creates a sense of immediacy, as if events are happening now", "It has no noticeable effect", "It only works for non-fiction"]', 1, 'Present tense narration makes events feel immediate and ongoing, as though they are happening in real time', 3, '10-11'),
('english', 'Creative Writing', 'What does "show, don''t tell" mean in creative writing?', '["Describe feelings directly, e.g. ''she was sad''", "Show emotions through actions and details rather than stating them directly", "Use only dialogue", "Avoid description entirely"]', 1, '"Show, don''t tell" encourages writers to reveal emotions through actions and sensory detail rather than simply stating them', 3, '10-11'),
('english', 'Creative Writing', 'Which opening line uses the most effective use of imagery to engage a reader?', '["It was a normal day.", "The day began like any other.", "Frost crept silently across the windowpane, sealing the world in silver.", "The weather was cold that morning."]', 2, 'This option uses vivid sensory imagery ("frost crept silently", "sealing the world in silver") to create a strong picture for the reader', 3, '10-11')

ON CONFLICT DO NOTHING;
